### ISSUE TITLE
Creator generating template with duplicated protocol

### ISSUE THREAD

**Issue by pvm30** [Azure/azure-api-management-devops-resource-kit#168]
A code like this in my JSON api specification:

![JSON-SPECIFICATION](https://user-images.githubusercontent.com/2522390/57130397-a1979300-6d99-11e9-9716-3df817b695a6.png)

generates an ARM template with duplicate protocols 

![DUPLICATED-PROTOCOLS-IN-TEMPLATE](https://user-images.githubusercontent.com/2522390/57130600-45813e80-6d9a-11e9-8103-ad7e6df5abfc.png)

When you try to deploy that template to Azure Resource Manager you get this error:

 **"message": "Supported API protocols must be unique"**  

![ERROR](https://user-images.githubusercontent.com/2522390/57130690-8f6a2480-6d9a-11e9-814a-8a5fdef467a9.png)

**Comment by miaojiang** [comment]
Thanks. This seems like a bug. We will investigate. 

cc @lucashuet93

**Comment by miaojiang** [comment]
Looks like we are using the Server component in Open API Spec to fill the "protocols" property of the API. We shouldn't be doing that because the "protocols" property is for the connection between client Apps and API Management. The value(s) of that field should come from the yaml config file, not from OAS (v3) or Swagger (v2).

We will get it fixed.

**Comment by pvm30** [comment]
Looking forward to that solution. Thanks in advance
