### ISSUE TITLE
[Extractor] API Extractor won't find API when having more than 100 records

### ISSUE THREAD

**Issue by DSpirit** [Azure/azure-api-management-devops-resource-kit#189]
### APIExtractor.cs - GetAPIsAsync

When an API Management instance has more than 100 API's it might happen, that the extract process won't work, as it can't find a given API in the list. I assume it's also not possible to extract more than 100 API's at once.

In order to solve this, the GetAPIsAsync in the APIExtractor.cs needs to loop over the response until it hasn't got a "nextLink" property.

**Comment by tsouva** [comment]
Hello, 
First, thank you for opening the issue.
I am totally new with APIM and I would like to resolve this problem too. You did gave a hint about the GetAPIsAsync but I have no idea how to should I modify it to make it works. Can I get more details on how to do it please?

**Comment by bremnes** [comment]
Welcome, @tsouva! Great that you want to contribute.

Now, for the task:

In [APIExtractor.cs](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/apimtemplate/Extractor/EntityExtractors/APIExtractor.cs) there are a number of api calls being made against Azure's REST api, like for instance [GetAPIsAsync](https://github.com/Azure/azure-api-management-devops-resource-kit/blob/master/src/APIM_ARMTemplate/apimtemplate/Extractor/EntityExtractors/APIExtractor.cs#L70). The Azure api it's calling is described on [Apis - List By Service](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apis/listbyservice), where you can also see an example of a response.

Some of the REST api's have a limit to how many results they return, but in order to be able to still retrieve all results they offer paging. That means that after your first call, you can inspect the result and if there is a url in the `nextLink`, well then you need to do one or multiple additional api calls to retrieve the complete set. Microsoft has some documentation on the general paging under [Async operations, throttling, and paging](https://docs.microsoft.com/en-us/rest/api/azure/#async-operations-throttling-and-paging).

If you want to fully re-produce the issue, you could for instance create a small script where you import an api 101 times in your api management service, and then run the extractor to see if they all are exported or if it's only 100. (I'm mentioning this because @DSpirit said that it _might_, so I'm not sure if it's an issue or not.)

To solve this, I imagine you either
* can set the `$top` parameter to a high number. I'd assume this is capped on 100 items, but you could give it a shot as that would be a quick fix.
* or need to inspect the response that you get back and see if there's a `nextLink`. If there is, retrieve the next page and add it to the result set. If that also has a `nextLink`, rinse and repeat until there's no `nextLink` being returned.
(I guess all the other api calls will have a similar limit, but we can deal with those later as this issue addresses the apis.)

Does that give you a starting point? Just shout out if there's anything else. We can go into more details regarding json deserialization and other implementation details if you want to.

**Comment by tsouva** [comment]
Thank you very much for your answer @bremnes, it did help me alot !
If you don't mind I would like to ask you another question which is, how do you only extract only a group or 1 specific API without getting all the API?

I did try the $filter to filter by the api name I choose on the parameter but it doesn't seems to work. Or maybe is my syntax wrong? 

Here is a my method (inspired by "GetAPIsAsync" in the APIExtractor.cs) : 

public async Task<string> **GetSingleAPIAsync**(string ApiManagementName, string ResourceGroupName, **string singleApiName**)
{
string requestUrl = string.Format("{0}/subscriptions/{1}/resourceGroups/{2}/providers/Microsoft.ApiManagement/service/{3}/apis?api-version={4}&**$filter=name eq {5}**", baseUrl, azSubId, ResourceGroupName, ApiManagementName, GlobalConstants.APIVersion, **singleApiName**);

return await CallApiManagementAsync(azToken, requestUrl);
}

**Comment by bremnes** [comment]
I think you need to enclose the value in apostrophes:
`{0}/subscriptions/{1}/resourceGroups/{2}/providers/Microsoft.ApiManagement/service/{3}/apis?api-version={4}&$filter=name eq '{5}'`

I tested it quick now in the [ARMExplorer raw](https://resources.azure.com/raw/) (let's you do Azure API calls without being "bothered" by authentication) and it worked fine.

I'm not sure how it relates to this issue though, but it could be a good fix as it seems like the current implementation is retrieving all the apis (well, at least the first 100) and then do a search through those.

**Comment by tsouva** [comment]
Hello, I did test it and it finally work ! 
Thank you very much ! @bremnes 
I want to know just in case I only need to extract 1 api without going thru all the API which will take lots of time.

Thank you again for your help. You just made my day !

**Comment by RupengLiu** [comment]
thanks @bremnes for resolving this issue!

**Comment by RupengLiu** [comment]
@DSpirit @bremnes this issue has been fixed by #318
