### ISSUE TITLE
Setting backend service url

### ISSUE THREAD

**Issue by MichalKosowski** [Azure/azure-api-management-devops-resource-kit#195]
Hi,

When using Creator tool and config.yaml to generate the templates, looks like the
`serviceUrl: url`
is ignored by Azure. I see it is correctly added to generated ARM template, but in created API there is always url from swagger:
1. If the swagger is attached as a file - Azure will pick up the url from host property of swagger.json file
2. If swagger file is attached as remote url - Azure will use that url as a backend service url.

**Expectation:**
Backend service url specified in config.yaml file or in ARM template is the one that will be used.

**Comment by punitganshani** [comment]
We also faced this same issue and used remote Swagger file to fix as interim solution till this fix

**Comment by miaojiang** [comment]
Will take a look.

**Comment by RupengLiu** [comment]
@MichalKosowski Thanks for reporting ! You are right ! The backend service don't support deploy swagger file and create api (with version set) at the same time, and the swagger file which comes later will always overwrite the backend url. 
Two ways to fix:
1. It can be fixed by creating a third api template to deploy and change the backend url, but it's not a good way
2. We are waiting the new backend service, which will solve this problem.

**Comment by RupengLiu** [comment]
resolved
