### ISSUE TITLE
How do i link user group Ids to products by group display name

### ISSUE THREAD

**Issue by Sacratees** [Azure/azure-api-management-devops-resource-kit#209]
I have found below example to associate user groups with the template. 

"type": "Microsoft.ApiManagement/service/products/groups",
"name": "[concat(parameters('ApimServiceName'), '/starter/developer' )]",

But in some of the old apim instances the identifier of the built-in group (Developers) was some numbers. So i get error as group not found.

Group name : Developer
Identifier : XXXXXXXXXXXXX

How can i get the user group identifier dynamically by the group display name ("Developers") in the template

**Comment by UmairSyed** [comment]
Are you using Extractor or Creator?

**Comment by bremnes** [comment]
@Sacratees, normally display names are not being used as references since they (usually) are editable and therefore can not be "trusted" in the long run. So that's why we use the identifier as a reference in the ARM templates.

Are you able to provide an example of the template if it's not working for you?

I haven't had the time to try it, but from the [service/products/groups template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/products/groups), I'd expect it to be similar to:
```
  {
    "type": "Microsoft.ApiManagement/service/products/groups",
    "name": "developers",  // or perhaps [concat(parameters('ApimServiceName'), '/developers')]
    "apiVersion": "2019-01-01"
  }
```
