### ISSUE TITLE
apimtemplate extract: Missing parameter <destinationApimName>

### ISSUE THREAD

**Issue by nicchidu** [Azure/azure-api-management-devops-resource-kit#244]
Would like to extract the apim service into files without deploying to another service (assuming that's missing destinationApimName error implies).

Thanks

**Comment by bremnes** [comment]
@nicchidu , when running the extractor, you won't automatically deploy to another instance. The extractor only generates the ARM files and put them locally on your disk (`--fileFolder` param), and that's it.

The reason why it's asking you to provide the `destinationApimName` is because it wants to put a value in the parameters file it generates. So just provide `--destinationApimName replace-me-destination-apim` and you can change it later if you want to. Or if you are doing some kind of configuration transformation on your CI/CD server, change it to whatever tokenization regime you are running:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "value": "replace-me-destination-apim"
    },
    "LinkedTemplatesBaseUrl": {
      "value": ""
    },
    "PolicyXMLBaseUrl": {
      "value": "https://replace-me-lat.er"
    }
  },
  "resources": []
}```

**Comment by nicchidu** [comment]
got it. thanks.
