### ISSUE TITLE
Validation fails when in AzDo with Extractor Files -> Looking for loggers template

### ISSUE THREAD

**Issue by travich** [Azure/azure-api-management-devops-resource-kit#307]
When I setup a validation task in AzDo, I see that it's looking for a loggers template which I do not have.  I setup just the basic conference example in my APIM and did not set up loggers.  I ran the extractor and my arguments looked something like the below.  

```
{
    "sourceApimName": "MySourceApim",
    "destinationApimName": "MyDestinationApim",
	"resourceGroup": "MyResourceGroup",
    "fileFolder": "c:\\src\\templates",
	"linkedTemplatesBaseUrl" : "https://testtesttest.blob.core.windows.net/conference",
	"policyXMLBaseUrl" : "https://testtesttest.blob.core.windows.net/conference/policies"
}

```
In the master template, you can see references to the logger, which is NOT generated.  When I run validation pointing to my master template and parameters I get the following error when it tries to copy the loggers template.

**2019-12-13T22:41:02.0372604Z There were errors in your deployment. Error code: InvalidContentLink.**

This is because it's looking for a file that isn't there, but has a section in the master template.

**Comment by RupengLiu** [comment]
Hi @travich , I just tested by extracting a basic api, on my end, the master template didn't contain reference to logger templates. Can I have more details? 
Several things may cause this problem, here i will name two most possible ones:
1. Make sure you have the newest version (after this commit https://github.com/Azure/azure-api-management-devops-resource-kit/commit/9c6b5848c01fab940e3a05625d5483a4c54232b0, since this commit has solved the issue you mentioned above)
2. Within your config file, do you include the "querystring"

If the above approaches didn't solve the problem, would mind send me an email to rupliu@microsoft.com with your master template, and detailed error information

Thanks

**Comment by travich** [comment]
I sent you an email with those details after double checking your steps I am still having a problem.

**Comment by RupengLiu** [comment]
@travich Hi, I just fixed the issue, thanks for your reporting!
One thing I notice is that if you want to extract one API, you can use "apiName" parameter, like 
```
{
    "sourceApimName": "MySourceApim",
    "destinationApimName": "MyDestinationApim",
    "resourceGroup": "MyResourceGroup",
    "fileFolder": "c:\\src\\templates",
    "apiName": "echo-api",
    "linkedTemplatesBaseUrl" : "https://testtesttest.blob.core.windows.net/conference",
    "policyXMLBaseUrl" : "https://testtesttest.blob.core.windows.net/conference/policies"
}
```
otherwise it will extract the whole apim instance, and it will extract the logger of this apim as well, this is also the reason you don't use logger for this API, while it will generate logger template.
