### ISSUE TITLE
Please bring back command line arguments to the extractor

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-api-management-devops-resource-kit#319]
With the latest update it appears you have to use extractorparams.json to define your arguments to the extractor tool. This prevents scenarios in which you need to pass dynamic values as arguments to the tool.

**Comment by RupengLiu** [comment]
Hi @joeyeng  can you elaborate the issue you have encountered so that we can have more background info ?

**Comment by joeyeng** [comment]
When I attempt to pass command line arguments, for example:

    dotnet run extract --sourceApimName "..." --destinationApimName "..." --resourceGroup "..." --fileFolder "." --linkedTemplatesBaseUrl "..." --policyXMLBaseUrl ".."

I get:

    Unrecognized option '--sourceApimName'

**Comment by RupengLiu** [comment]
Hi @joeyeng  the original intention to use extractorparams.json is that as the number of params increases / and to parameters more values (backendurl, serviceurl, named value) in the future, command line arguments will become very long. 

Also using this json file, you can pass any dynamic values as arguments like before.

**Comment by joeyeng** [comment]
Yes, it is a lot of arguments, but it's more flexible when needed. Is it
possible for the tool to support both methods of passing arguments?

**Comment by RupengLiu** [comment]
@joeyeng ,it's possible, but it depends on schedule @miaojiang

**Comment by miaojiang** [comment]
Triaged. Added to the backlog.

**Comment by bremnes** [comment]
I agree with @joeyeng that it should be possible to pass command line arguments for all the properties. For our own project we are calling this library in-memory so it's nice to not be required to write temporary files to disk.

@joeyeng , could you do me a favour and give my feature branch a spin to see if that solves your problem? [319-extractor-command-line-arguments](https://github.com/bremnes/azure-api-management-devops-resource-kit/tree/319-extractor-command-line-arguments)

What I've done is that the application reads the file from disk _if_ `extractorConfig` is specified, and then it reads arguments from the command line. If the command line has the same arguments that has been specified in the file, command line wins.
(In addition the commands are reflected from the `ExtractorConfig` class so that command line and file reader should be in sync.)

**Comment by joeyeng** [comment]
Thanks @bremnes! I'll let you when I have time to try it out.

**Comment by joeyeng** [comment]
Hey @bremnes, I tested out your branch and it works great.
