### ISSUE TITLE
Merge multiple development APIM into a single shared APIM

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-api-management-devops-resource-kit#349]
Any suggestions for doing something like this?

We have multiple developer teams each working in their own development APIM, and we would like to offer a single shared APIM. This means that each team must only be allowed to deploy parts of their own APIM, and we must make an effort that no team can change other teams APIs and other settings in the shared APIM.

**Comment by miaojiang** [comment]
Hi @spaelling , is there a specific area where you need suggestions?

**Comment by spaelling** [comment]
I figured that I will keep different folders for each seperate API management service, and then I will ensure that each resource has some unique prefix, or other way to differentiate.
I am using PR webhooks in Azure DevOps to validate each PR and make sure it does not violate anything that could overwrite existing APIs from a different API management service.

I was more wondering if you have had this request before. In my case each team wants their own API management service for development, but we cannot allow them to also have one in production due to costs.

**Comment by bremnes** [comment]
@spaelling, I think the most pragmatic way would be to do as you've suggested: use pull requests and then review with a custom policy or manually.

This is a slippery slope with a lot of administration, but I'll mention it:

If you want to really lock things down, you could venture into the RBAC and permissions maze. Through the portal the roles and permissions are usually set on a higher level, such as on the entire APIM instance; do you want this person to have the role 'API Management Service Reader', 'API Management Service Contributor' or 'API Management Service Operator'. (You can create custom roles as well.)

However, since a resource is a resource you can set permissions on much lower level, such as products, apis etc. And you can scope these permissions on both users and service principals.

So you could for instance have multiple service principal/service connections in AzDO where each one is limited to the apis for that team. Different build/release pipelines which are triggered on the different teams check-ins using path filters. If a team attempts to deploy an api they are not allowed to, they will get a hard error since the service account they are using is not permitted to do so.

Example through the cli:
`az role assignment create --assignee-object-id <aad object id> --role <role name> --scope <resource id>`
`az role assignment create --assignee-object-id 196b0696-9a3a-427d-b6e8-de6df38359c5 --role "API Management Service Contributor" --scope /subscriptions/c8d5716c-6865-4a90-bfb2-9919c3d2fd80/resourceGroups/my-shared-resourcegroup/providers/Microsoft.ApiManagement/service/my-shared-apim/apis/petstore-api`

**Comment by spaelling** [comment]
> 
> 
> @spaelling, I think the most pragmatic way would be to do as you've suggested: use pull requests and then review with a custom policy or manually.
> 
> This is a slippery slope with a lot of administration, but I'll mention it:
> 
> If you want to really lock things down, you could venture into the RBAC and permissions maze. Through the portal the roles and permissions are usually set on a higher level, such as on the entire APIM instance; do you want this person to have the role 'API Management Service Reader', 'API Management Service Contributor' or 'API Management Service Operator'. (You can create custom roles as well.)
> 
> However, since a resource is a resource you can set permissions on much lower level, such as products, apis etc. And you can scope these permissions on both users and service principals.
> 
> So you could for instance have multiple service principal/service connections in AzDO where each one is limited to the apis for that team. Different build/release pipelines which are triggered on the different teams check-ins using path filters. If a team attempts to deploy an api they are not allowed to, they will get a hard error since the service account they are using is not permitted to do so.
> 
> Example through the cli:
> `az role assignment create --assignee-object-id <aad object id> --role <role name> --scope <resource id>`
> `az role assignment create --assignee-object-id 196b0696-9a3a-427d-b6e8-de6df38359c5 --role "API Management Service Contributor" --scope /subscriptions/c8d5716c-6865-4a90-bfb2-9919c3d2fd80/resourceGroups/my-shared-resourcegroup/providers/Microsoft.ApiManagement/service/my-shared-apim/apis/petstore-api`

Appreciate the suggestions. I did not consider using RBAC on each resource, but I am not sure if I would know resource Ids ahead of a PR or if the resources would change rapidly. But it could be an extra safety measure that the AzDO pipeline could only alter existing resources, and then some sort of approval flow for bringing new ones in. I will consider that.

Another thing I can use it for is to grant read access to relevant resources within the shared production APIM for each team, so they would not even be able to see each others APIs, etc.

**Comment by adrianhall** [comment]
We published the following document for discussing this scenario.

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops

Since there are no code changes involved here, I'll close this issue.

**Comment by adrianhall** [comment]
We published the following document for discussing this scenario.

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/devops/automated-api-deployments-apiops

Since there are no code changes involved here, I'll close this issue.
