### ISSUE TITLE
Combine initial and subsequent templates

### ISSUE THREAD

**Issue by miaojiang** [Azure/azure-api-management-devops-resource-kit#434]
It should no longer be needed to create two templates for an API.

**Comment by levimatheri** [comment]
Any update on this? I'm having trouble deploying versions. This is because the `path` property is defined in both initial and subsequent templates. Therefore I cannot deploy two or more versions with the same `path`/`suffix`. It fails with the following error: `API with specified URL path '' already exists.`. I tried deploying just the subsequent templates and that worked.

**Comment by springcomp** [comment]
This is fixed in #575 while still keeping both templates.

**Comment by adrianhall** [comment]
Believe this to be fixed.  If you are still having trouble deploying multiple versions because of the same suffix, please open a new issue with the required information.
