### ISSUE TITLE
Extractor no longer extracts Product template this is a must

### ISSUE THREAD

**Issue by gpr511** [Azure/azure-api-management-devops-resource-kit#471]
When using the extractor to extract a single API it is no longer extracting the Product template.
This is needed as part of our deployment pipeline to create the Product if it does not exist.

Looks like it has been removed from the APIExtractor.cs (22/02/2021 17:58:55) can anyone explain why?

**Comment by DSpirit** [comment]
@RupengLiu actually I've just stumbled upon something confusing:
The **ProductAPIs** and **TagAPIs** get extracted twice:
1. In the APIExtractor both get extracted
2. In the TagAPIExtractor the API Tags get extracted.
3. In the ProductAPIExtractor the API Products get extracted.

In my current version of the resource kit, I've actually removed the `#region API Tags ` and the `#region API Products` from the `GetRelatedTemplateResourcesAsync`  so that I'll have clean templates for API's, Tags, Products, ProductAPIs, TagAPIs.
But now they need to get deployed *separately*.

I think in the long term the API Extractor should extract only the API itself and not the dependent resources or am I wrong?
So I guess the diagnostic settings will be excluded, too? 

Here's my version:
https://github.com/Azure/azure-api-management-devops-resource-kit/compare/master...DSpirit:patch-5
