### ISSUE TITLE
Single API with revisions / versions issues

### ISSUE THREAD

**Issue by biancafrigerioMS** [Azure/azure-api-management-devops-resource-kit#479]
Hello,

I'm trying to implement two scenarios with a customer and I'm facing some issues:

1. When I try to extract from APIM1 and deploy to APIM2 a **single API with all revisions** _(dotnet run extract --sourceApimName $(sourceApimName) --destinationApimName $(destinationApimName) --apiName "api-todoitem" --includeAllRevisions true --resourceGroup APIM --fileFolder $(Build.ArtifactStagingDirectory)\APIM))_ in the deployed resource APIM2 the "current" revision, and the "online/offline" revisions are not correctly deployed (the current revision remains the first one and all the revisions in APIM2 are online while in APIM1 only 3 of 7 are online). 
2. When I try to extract from APIM1 and deploy to APIM2 a **single API with all versions** _(dotnet run extract --sourceApimName $(sourceApimName) --destinationApimName $(destinationApimName) --resourceGroup APIM --apiVersionSetName 604f8727f1fe594343481e4a --fileFolder $(Build.ArtifactStagingDirectory)\APIM_v)_ it cannot find the versionSetName; It exist and I retrieved it with: _az apim api versionset list --resource-group APIM --service-name APIMxx  --output table_.

Could you please help me in solving this issues?

Thank you

Bianca

**Comment by miaojiang** [comment]
@RupengLiu please take a look.

**Comment by tasb** [comment]
I think that the second issue can be related with this issue I found: https://github.com/Azure/azure-api-management-devops-resource-kit/issues/442#issuecomment-852362148

I'm creating a pull request for the correction

**Comment by f-alizada** [comment]
Hello @biancafrigerioMS.
Thank you for reporting the issue. 
Please be informed that the changes (https://github.com/Azure/azure-api-management-devops-resource-kit/pull/782) addressing the revisions functionality are merged into the main branch, hence closing the issue.

Regarding the changes: 
 1. When one single API with all revisions is extracted, for each current API api-release template is generated, in order to make the revision of API current, api-release template should be deployed as well. 
 2. IsOnline property is added to the exported templates. (IsOnline property will be applied to the APIs which are already existing during the deployment). 
 3. Extracting single API with all versions: from the input it seems that the provided apiVersionSetName is not a displayName of the versionSet. It should be solved using the display name. As an action item documentation will be updated. 

Please feel free to reopen the issue or create a new one in case you will face some problems with API revisions/versions

Best regards.
