### ISSUE TITLE
Turn .NET Core command line project into an 'executable' command

### ISSUE THREAD

**Issue by miaojiang** [Azure/azure-api-management-devops-resource-kit#49]

**Comment by odaibert** [comment]
In order to generate an executable instead of a dll, you need to choose a processor architecture to the build command like this:

> dotnet build -r osx.10.12-x64

more info [HERE](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog?irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir__hsowk3knackfrzna0higqpq2m22xhuzs6t1e6gnn00)(7593)(1243925)(je6NUbpObpQ-Mq6_9zHv7EwQSmKj87vuEQ)()&irclickid=_hsowk3knackfrzna0higqpq2m22xhuzs6t1e6gnn00#using-rids?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-Mq6_9zHv7EwQSmKj87vuEQ&epi=je6NUbpObpQ-Mq6_9zHv7EwQSmKj87vuEQ)

**Comment by nzthiago** [comment]
This was done as part of our first release:
https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/v0.1-alpha
