### ISSUE TITLE
[Creator] create custom parameters in arm template

### ISSUE THREAD

**Issue by agarwalarjun123** [Azure/azure-api-management-devops-resource-kit#541]
currently the only supported that can be environment specific are URLs and API Management Instance Name.
There is a great need for passing custom parameters while generating arm templates.

**Comment by levimatheri** [comment]
@agarwalarjun123 We've had to modify the creator tool to parameterize other fields that we needed e.g. display name and suffix. But yes I agree, this is a much needed feature.

**Comment by levimatheri** [comment]
@agarwalarjun123 Check out [this tool](https://github.com/mirsaeedi/dotnet-apim)

**Comment by adrianhall** [comment]
It isn't clear how this would be used.  Could you provide an example of what you would do and how it would be useful?

**Comment by adrianhall** [comment]
Closed due to lack of information.

If you have a specific case where a field needs to be parameterized, please open a new issue asking for it with the specifics.

Thank you.

**Comment by levimatheri** [comment]
We decided to use dotnet-apim. It provides variable replacement for ANY property. https://github.com/mirsaeedi/dotnet-apim#variables

**Comment by levimatheri** [comment]
@adrianhall Instead of requesting a new GitHub issue for each field, couldn't you follow something similar to [dotnet-apim](https://github.com/mirsaeedi/dotnet-apim#variables), where customers can parameterize ANY field? dotnet-apim also allows you to parameterize policy files, as well as add [conditionals](https://github.com/mirsaeedi/dotnet-apim#conditional-statements). 
On top of that, in dotnet-apim we don't have to deal with staging files to a storage account for linked templates, the entire API template is generated as ONE file. The workflow is WAY easier to setup and maintain. I'd suggest you take a look at it.

**Comment by adrianhall** [comment]
I love the dotnet-apim project.  If that mechanism works for you, is there a reason you want to use creator instead?

**Comment by levimatheri** [comment]
I guess only reason would be creator is maintained by Microsoft..
