### ISSUE TITLE
QUESTION: How to prevent Extractor from touching Application Insights settings?

### ISSUE THREAD

**Issue by mzrzz3** [Azure/azure-api-management-devops-resource-kit#559]
We are using Terraform to create and maintain the APIM instances. I only want to use the APIM devops resource kit to extract API specific resources such as the API definition and policies. 

I don't want to have to parameterize Application Insights resource Ids and LoggerIds.

How do I prevent the extractor from extracting information about Application Insights? 

Why is this even a feature?

**Comment by adrianhall** [comment]
If you extract just an API, then all the information about an API is extracted - that includes anything that you enter in the APIs blade on Azure Portal.  Since you are using Terraform already, I suggest you use Terraform to define APIs rather than using extraction.  It will be more maintainable for you in the long run.
