### ISSUE TITLE
Wrong apiVersion for "type": "Microsoft.Resources/deployments" in master.template.json

### ISSUE THREAD

**Issue by kboro** [Azure/azure-api-management-devops-resource-kit#665]
'Create' action generates 'master.deployment.json' according to .yml file. 

However during master.template.json deployment it fails with:

**"'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template resource 'globalServicePolicyTemplate' at line '19' and column '5' is invalid. 'ApiVersion' property is invalid. The supported versions are '2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,202"**

in master.deployment.json I can see there not supported for "Microsoft.Resources/deployments" apiVersion added:

"apiVersion": "2021-08-01",
      "type": "Microsoft.Resources/deployments",
      "name": "productsTemplate",

**Comment by adrianhall** [comment]
Thank you for the report.

Can you please provide:

1. The version of the tooling you are using?
2. The configuration file you are using?
3. Any logs you received when running (use a gist / feel free to obscure any secrets)

**Comment by kboro** [comment]
Hello,


1. 1.0.0-beta.1

2:

`version: 0.0.1
apimServiceName: ${apimInstanceName}$   # Required, must match name of an apim service deployed in the specified resource group
policy: ${apimBasePath}$/XMLPolicies/global.xml

apis:
    - name: CompaniesAPI
      description: Api provides the possibility to manage companies
      type: http
      serviceUrl: https://func-loady-company-euw-${env}$.azurewebsites.net/api
      displayName: Companies API
      openApiSpec: ${apimBasePath}$/OpenAPISpecs/Companies.API.openapi.json    # Required, can be url or local file
      policy: ${apimBasePath}$/XMLPolicies/companies/companies-all-operations.xml
      suffix: api/companies
      apiRevision: 1
      products: Starter, Unlimited
      tags: Companies
      protocols: https
      subscriptionRequired: false
      isCurrent: true
      operations:
          create-company: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/companies/companies-create-company.xml
          delete-company: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/companies/companies-delete-company.xml
          get-all-companies: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/companies/companies-get-all.xml
         
      subscriptionKeyParameterNames: 
         header: Ocp-Apim-Subscription-Key
         query: subscription-key
      authenticationSettings:
        oAuth2:
            authorizationServerId: oauth
      diagnostic:
        name: applicationinsights
        alwaysLog: allErrors
        loggerId: appinsights-euw-${env}$
        sampling:
          samplingType: fixed
          percentage: 0
        frontend: 
          request:
            headers:
            body: 
              bytes: 0
          response: 
            headers:
            body: 
              bytes: 0
        backend: 
          request:
            headers:
            body: 
              bytes: 0
          response: 
            headers:
            body: 
              bytes: 0
        enableHttpCorrelationHeaders: true

    - name: LoadingPointsAPI
      description: Api provides the possibility to manage loading points
      type: http
      serviceUrl: https://func-loady-loading-euw-${env}$.azurewebsites.net/api
      displayName: Loading Points API
      openApiSpec: ${apimBasePath}$/OpenAPISpecs/Loading.API.openapi.json    # Required, can be url or local file
      policy: ${apimBasePath}$/XMLPolicies/loadingpoints/loading-all-operations.xml
      suffix: api/loadingpoints
      apiRevision: 1
      products: Starter, Unlimited
      tags: LoadingPoints
      protocols: https
      subscriptionRequired: false
      isCurrent: true
      operations:
          post-create: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/loadingpoints/loading-create.xml
          delete-loading-point: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/loadingpoints/loading-delete.xml
  
      subscriptionKeyParameterNames: 
         header: Ocp-Apim-Subscription-Key
         query: subscription-key
      authenticationSettings:
        oAuth2:
            authorizationServerId: oauth
    
    - name: ProductsAPI
      type: http
      description: Api provides the possibility to manage products
      serviceUrl: https://URL
      displayName: Products API
      openApiSpec: ${apimBasePath}$/OpenAPISpecs/Products.API.openapi.json    # Required, can be url or local file
      policy: ${apimBasePath}$/XMLPolicies/products/products-all-operations.xml
      suffix: api/products
      apiRevision: 1
      products: Starter, Unlimited
      tags: Product
      protocols: https
      subscriptionRequired: false
      isCurrent: true
      operations:
          create: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/products/products-create.xml
          getall: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/products/products-get-all.xml
          getbyid: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/products/products-get-by-id.xml
          update: # it's operation id
              policy: ${apimBasePath}$/XMLPolicies/products/products-update.xml
      subscriptionKeyParameterNames: 
         header: Ocp-Apim-Subscription-Key
         query: subscription-key
      authenticationSettings:
        oAuth2:
            authorizationServerId: oauth


tags:
  - name: Companies
    displayName: Companies

  - name: LoadingPoints
    displayName: LoadingPoints

  - name: Product
    displayName: Product


products:

    - name: Starter
      displayName: Starter
      description: Subscribers will be able to run 5 calls/minute up to a maximum of 100 calls/week.
      subscriptionRequired: true
      approvalRequired: false
      subscriptionsLimit: 1
      state: published

    - name: unlimited
      displayName: Unlimited
      description: Subscribers have completely unlimited access to the API. Administrator approval is required.
      subscriptionRequired: true
      approvalRequired: true
      subscriptionsLimit: 1
      state: published

        
namedValues:
    - name: company-key
      displayName: company-key
      value: ${key_company}$
      secret: true
    - name: loading-key
      displayName: loading-key
      value: ${key_loading}$
      secret: true
    - name: product-key
      displayName: product-key
      value: ${key_product}$
      secret: true
   
authorizationServers:
    - displayName: oauth
      description: authserrver
      clientRegistrationEndpoint: https://${URL}$
      authorizationEndpoint: https://${adb2cName}$.b2clogin.com/${adb2cName}$.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_sign_in_and_sign_up
      authorizationMethods:
        - GET
      tokenEndpoint: https://${adb2cName}$.b2clogin.com/${adb2cName}$.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_sign_in_and_sign_up
      supportState: false
      defaultScope: ${scopes}$
      clientAuthenticationMethod:
        - Body
      grantTypes:
        - authorizationCode
      bearerTokenSendingMethods:
        - authorizationHeader
      clientId: ${clientId}$
      clientSecret: ${clientSecret}$

loggers:
    - name: appinsights
      loggerType: applicationInsights
      description: a test app insights
      credentials:
        instrumentationKey: ${instrumentationkey}$
      isBuffered: false
    
backends:
 
    - name: company
      title: company
      description: company
      url: https://company.azurewebsites.net/api
      protocol: http
      credentials:
        header: 
          x-functions-key:
            - "{{company-key}}"

    - name: loading
      title: loading
      description: loading
      url: https://loading.azurewebsites.net/api
      protocol: http
      credentials:
        header: 
          x-functions-key:
            - "{{loading-key}}"

    - name: product
      title: product
      description: product
      url: https://product.azurewebsites.net/api
      protocol: http
      credentials:
        header: 
          x-functions-key:
            - "{{product-key}}"


outputLocation: ${apimBasePath}$/output/
baseFileName: base
linked: true # Optional
linkedTemplatesBaseUrl : https://${BLOB_URL}$
serviceUrlParameters: 
  - apiName: CompaniesAPI
    serviceUrl: https://company.azurewebsites.net/api
  - apiName: LoadingPointsAPI
    serviceUrl: https://loading.azurewebsites.net/api
  - apiName: ProductsAPI
    serviceUrl: https://products.azurewebsites.net/api
`

**Comment by mk-khan** [comment]
@adrianhall , i am also having same issue with beta version or the current main repo. It happens in dev ops pipeline when trying to validate generated apim files. Not sure whats the issue, tried the last release as well still have the same issue. Any help greatly appreciated .. I just want to extract complete apim download from one subscription and upload it to the next one, tried lots of version, sometime getting tags error or if tag error is gone then this validation error, its not isolated to just this global policy file, it has also come with other files namevalue.. i think since the latest code has tried to update the API version to 2020-08-01, this issue is introduced

`Checking if the following resource group exists: rg-test-300.
Resource group exists: true.
Creating deployment parameters.
The detected encoding for file 'apimExtract-prod\apim--prod-master.template.json' is 'utf-8'
(node:1780) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
The detected encoding for file '\apimExtract-prod\apim-prod-parameters.json' is 'utf-8'
Starting template validation.
Deployment name is apim-prod-master-20220411-225931-2bbb
There were errors in your deployment. Error code: InvalidTemplate.
##[error]Deployment template validation failed: 'The template resource 'globalServicePolicyTemplate' at line '1' and column '786' is invalid. 'ApiVersion' property is invalid. The supported versions are '2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'. Please see https://aka.ms/arm-template/#resources for usage details.'.
`
`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "type": "string"
    },
    "PolicyXMLBaseUrl": {
      "type": "string"
    }
  },
  "resources": [
    {
      "properties": {
        "value": "[concat(parameters('PolicyXMLBaseUrl'), '/globalServicePolicy.xml')]",
        "format": "rawxml-link"
      },
      "name": "[concat(parameters('ApimServiceName'), '/policy')]",
      "type": "Microsoft.ApiManagement/service/policies",
      "apiVersion": "2019-01-01"
    }
  ]
}`

**Comment by DeagleGross** [comment]
@mk-khan @kboro Thanks a lot for noticing and submitting an issue. I am sorry for you having some troubles and I didn't have much time to look into it - I will do it ASAP (1-2 days).

We have refactored a lot of code in last time and such troubles can occur, so if anything else happens dont hesitate to submit a new issue.

**Comment by mk-khan** [comment]
Thank you for your reply, is there a working version that I can use at the
moment? I tried few older one as well but was not successful to generate
and import.. appreciate if you can share link to code or executable that
can be used to extract and will pass the validation for all of the APIs in
apim .. forward to hearing from you

I look forward to hearing from you soon

**Comment by DeagleGross** [comment]
@mk-khan If you want to run urgently, you can try unrefatored old version, using i.e. this commit - https://github.com/Azure/azure-api-management-devops-resource-kit/tree/adc971f7eb55a429b979473ec2f8aecc375b4428

If that works for you, please, let me know. Probably it will help me with bug-fix.

**Comment by mk-khan** [comment]
@DeagleGross 
Thanks for the link, i tried extracting using that link. Dont have any issue with extraction part. However, when i try to validate this in the pipeline i am still getting the same error 


`There were errors in your deployment. Error code: InvalidTemplate.
##[error]Deployment template validation failed: 'The template resource 'namedValuesTemplate' at line '1' and column '786' is invalid. 'ApiVersion' property is invalid. The supported versions are '2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'. Please see https://aka.ms/arm-template/#resources for usage details.'.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
`

this is the output of apiversion in namevaluetemplate file
`{
      "apiVersion": "2021-08-01",
      "type": "Microsoft.ApiManagement/service/namedValues",
      "name": "[concat(parameters('apimServiceName'), '/auth-200')]",
      "properties": {
        "secret": false,
        "displayName": "auth-200",
        "value": "12345"
      }
    }`

I believe the issue is with the code which is outputting apiversion 2021-08-01

**Comment by DeagleGross** [comment]
@kboro @mk-khan I have fixed that - the apiVersion for Microsoft.Resources was not the correct one. Thanks for a great logs\error pointing.

Let me know if that works or not (please, use last main)

**Comment by mk-khan** [comment]
Hi @DeagleGross  thanks for the quick fix, I checkout Main branch and able to pass through that error, however now I am getting this error 

There were errors in your deployment. Error code: InvalidTemplate.
##[error]Deployment template validation failed: 'The template resource 'apim-test-eastau-300/to-api/put-caseid' at line '13160' and column '5' is not valid: Unable to evaluate template language function 'resourceId': the type 'Microsoft.ApiManagement/service/apis/operations' requires '3' resource name argument(s). Please see https://aka.ms/arm-template-expressions/#resourceid for usage details..


A quick google is showing me result as 
[resourceId('Microsoft.ApiManagement/service/apis/schemas', 'Api Management Resource Name', 'Api Name', 'Schema Name')]

it should be somethig with three param but current extractor is extracting with two params .. it seems.. any help is much appreciated

**Comment by DeagleGross** [comment]
Hey @mk-khan, I am happy to help you. But can we, please, move to another issue, because I will definitely forget about this eventually. It is much easier to plan and fix things one-by-one :)

Also, please, take advantage of issue template to input all information regarding the bug.
Thanks for collaboration, sorry for double-work
