### ISSUE TITLE
[Extractor] Cannot deploy API resource with a revision.

### ISSUE THREAD

**Issue by ayuina** [Azure/azure-api-management-devops-resource-kit#731]
## Where did you encounter this bug?

* Extractor

## Describe the bug

I get some errors when dploying arm template which was generated by extractor.

- The name of api resource doesn't contains revision in basefilename-api.template.json
  - resource name is just "[concat(parameters('apimServiceName'), '/test-api')]", but other resources in same file depends on "[resourceId('Microsoft.ApiManagement/service/apis', parameters('apimServiceName'), 'test-api;rev=2')]"
  - The workarround is manually adding revision name of api, but it will be overrided when extract next time.
- Cannot change current revision
  - "ValidationError" occurs when deploy api which "isCurrent: true when other revision is CURRENT.
  - The workarround is set isCurrent=false after extract and before deployment.

## What version of the DevOps Resource Kit is being used?

1.0.0-beta.4

## What version of dotnet are you running?

6.0.300

## What platform (OS and version) are you running on?

Windows, not WSL

## The command line you are running?

dotnet run extract --extractorConfig .\extractSettigs.json   

## The configuration file being used?

```json
{
    "sourceApimName" : "apim-dev",
    "destinationApimName": "apim-prod",
    "resourceGroup": "myRgName",
    "fileFolder" : "extractor-output",

    "linkedTemplatesBaseUrl" : "https://hoge.storage.url/container/",
    "linkedTemplatesSasToken": "?sastoken=goeshere&type=linkedTemplate",
    "policyXMLBaseUrl":  "https://hoge.storage.url/container/policies/",
    "policyXMLSasToken": "?sastoken=goeshere&type=policyXml",

    "apiName" : "test-api",
    "includeAllRevisions" : true,
    "baseFileName" : "apiconfig"
}
```

## How is your API Management Instance set up?

I created my APIM Developer SKU as Owner of subscritpion. VNet is not configured.

## What logs (if any) were produced?

```json
{
    "status": "Failed",
    "error": {
        "code": "ValidationError",
        "message": "One or more fields contain incorrect values:",
        "details": [
            {
                "code": "ValidationError",
                "target": "IsCurrent",
                "message": "Can't set new revision as current."
            }
        ]
    }
}
```

## Expected behavior

The extracted file should be deployed without no change, becase I want edit API definitions in the Azure portal(or Azure CLI).

**Comment by f-alizada** [comment]
Hello @ayuina. 
Thank you for reporting the issue. 
Please be informed that the changes (https://github.com/Azure/azure-api-management-devops-resource-kit/pull/782) addressing the bug are merged into the main branch and will be available in the future releases, hence closing the issue. 

Regarding the changes: 
IsCurrent property is removed from generated templates and was replaced with additional template Api release.
In order to make the Api current, api-release template should be deployed as well
Release template will be generated for each api revision which is current (given extractor parameters: single Api with all revisions)
Api-release template will include release resources for each current Api if all APIs are extracted

If you will face issues with revisions, please feel free to open a new issue or reopen this one.

Best regards
