### ISSUE TITLE
Feature Request (extractor):  make an option to handle shared named values

### ISSUE THREAD

**Issue by davidliuhca** [Azure/azure-api-management-devops-resource-kit#779]
### Scenario

Let's say a web server hosts many .NET apis. All these apis share the same base url like: {{baseURL}}/serviceA.svc, {{baseURL}}/serviceB.svc

namedValue baseURL is shared by many APIs. Let's say service A is deployed to the Prod. After several months the host is changed so the baseURL changed while deploying service B. Now baseURL has the new value.

After another couple of months service A need to be recovered from the release pipeline A. Unfortunately the repo for release pipeline A still has the old value for baseURL. Thus it will make all apis hosting in that host fail

### Proposal

make it an option to remove the shared namedValues from the namedValue template

**Comment by adrianhall** [comment]
As with the global policy one, I don't think you are thinking of this the right way.  You should be extracting all dependent APIs.

Unlike the global policy one, there is no easy solution to this.  I'd suggest looking at APIOps in the Azure Architecture Center and at https://github.com/azure/apiops as an alternative framework - it works off a git checkin rather than an ARM template and seems better suited for what you are doing.

**Comment by davidliuhca** [comment]
I will have a look at APIOps. thanks.

Currently I have a dedicated pipeline to deploy shared namedValue only, and
shared namedValue are excluded from the templates of individual APIs'
templates
